### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by KokosnussDEV** [DrKain/steam-market-search#2]
How can I change the currency, or is there a table of numbers for different currencies?

**Comment by DrKain** [comment]
DoctorMcKay's [steam-user](https://www.npmjs.com/package/steam-user) has a file with all the currency codes: [ECurrencyCode.js#L4-L45](https://github.com/DoctorMcKay/node-steam-user/blob/master/enums/ECurrencyCode.js#L4-L45).  
You should be able to pass `currency: 5` in the search.  
  
```javascript
SteamMarket.search("578080", { find : "Trenchcoat", currency: 5 })
```

**Comment by DrKain** [comment]
Scratch the last comment, it looks like this doesn't work anymore, it defaults to USD regardless of the currency parameter or server location.    
I'll dig around for another way but in the mean time you should be able to convert the prices using [fixer.io](https://www.npmjs.com/package/fixer.io) or another currency conversion package.
