### ISSUE TITLE
not enough results while searching.

### ISSUE THREAD

**Issue by supernoob180799** [DrKain/steam-market-search#4]
I started searching for "cases" then it shows only the weapon skins with tag case. I believe there are not enough number of search result outputs. As when I am entering "clutch case" the output gives the better output.
Here goes the code.

```javascript
market.setRequestOptions({
    count: 100
});

market.searchCSGO('case').then(results => {
    for(result of results){
        var res = result.asset_description;
        if(res.type=='Base Grade Container'){
            console.log(res.type);  
        }
    }
});
```

**Comment by DrKain** [comment]
This is an issue with steam, not the package.
Steam limits the number of results per page to 100. You can pass the `start` parameter to load the next page of items.  
If you set the count to `100` then you need to increment `start` by 100 for each page.  

Here's a example script that should help you with loading multiple pages of items:  
https://gist.github.com/DrKain/b05c210678a1bc8f55a19e5575ea2f30

**Comment by supernoob180799** [comment]
Yeah, thanks that worked.
