### ISSUE TITLE
CSGO Pattern ID and Float

### ISSUE THREAD

**Issue by locko200** [DrKain/steam-market-search#5]
I want to search for certain items and I need to know their exact pattern ID and float. How do i check them?

**Comment by DrKain** [comment]
This package can only fetch the inspect link for items listed on the market. You will need to pass it to another package that can inspect the item and retrieve the paintwear (float).

[https://www.npmjs.com/package/globaloffensive](https://www.npmjs.com/package/globaloffensive#inspectitemowner-assetid-d-callback)  
https://www.npmjs.com/package/tf2
