### ISSUE TITLE
Is game_appid not implemented yet?

### ISSUE THREAD

**Issue by RudeySH** [DrKain/steam-market-search#6]
The readme mentions `game_appid` can be used to filter trading cards by game. The code also contains the following comment:

```ts
/**
 * The AppID of the game you want to fetch cards, boosters, emoticons, backgrounds for.
 * appid must be 753 for this to work
 */
game_appid?: number | null;
```

And yet, this doesn't seem to be implemented? I can't get it to work. It seems no such parameter actually exists on the Steam Market API.

**Comment by DrKain** [comment]
`game_appid` was a thing 3-4 years ago when this package was originally made. The update last year switched from JavaScript to TypeScript while leaving most of the original code as it was.  
  
You can still filter using the game appid:

```js
// Search for steam community items from the game "100% Orange Juice" 
market.search(753, { 'category_753_Game[]': 'tag_app_282800', query: 'stars' });
```

**Comment by DrKain** [comment]
Adding onto this, If you want to filter by multiple games you can pass an array instead. I'll be updating the readme shortly, thanks for opening an issue. 
   
```js
'category_753_Game[]': ['tag_app_282800', 'tag_app_501900']
```

**Comment by RudeySH** [comment]
Thanks for the detailed reply! I was poking around the Steam Market but I couldn't find this anywhere. I don't think there's a way to filter community items by app in their UI. How did you figure out that the app ID values should be prefixed with ` tag_app_`?

**Comment by DrKain** [comment]
You can fetch all available filters for each app using the API:  
https://steamcommunity.com/market/appfilters/753   
 
This is the resource used to populate the "advanced search" forms. Each tag will also appear in the URL
![1](https://i.imgur.com/053p5N5.png)
