### ISSUE TITLE
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.

### ISSUE THREAD

**Issue by KostaD02** [DrKain/steam-market-search#8]
Working with angular 12 and got error : 
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
- install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "https": false }

is there any way to fix ? (searched fixes but didn't worked for me )

**Comment by DrKain** [comment]
Your issue is with angular/webpack, not this package. I can't provide much support here.  

This thread should assist you:    
https://github.com/angular/angular-cli/issues/20819#issuecomment-842307462

**Comment by KostaD02** [comment]
Thanks i found this comment aswell but can't make it work , hope stackoverflow got answer for me

**Comment by DrKain** [comment]
As an extra note you probably shouldn't be using this package through the browser.   
Ideally you'd make the requests back-end and serve the results through an API

**Comment by KostaD02** [comment]
Unfortunately don't know back-end to build , so trying to make angular&firebase project
